### ISSUE TITLE
Recommend using go mod

### ISSUE THREAD

**Issue by shenwei356** [cmdoret/dnaglider#3]
Hi Cyril, I notice this repo calls https://github.com/shenwei356/unikmer, which I have split into several repositories:

- [kmers](https://github.com/shenwei356/kmers), a package of kmer (sketch) related operations.
- [sketches](https://github.com/shenwei356/bio/tree/master/sketches) provides iterators for k-mer and k-mer sketches.
- [unik](https://github.com/shenwei356/unik) provides k-mer serialization methods for the package.
- [bio/taxonomy](https://github.com/shenwei356/bio/tree/master/taxdump), a package of NCBI taxonomy operations.

I'd like to recommend using go mod for better dependency management so this repo would be correctly installed via `go get`.

**Comment by cmdoret** [comment]
Hi @shenwei356,

Thanks for your message, I have updated dependencies and setup go mod :)

Best,
Cyril
